#!/opt/bin/stackless-python

from sheared.web.entwiner import Entwiner
from sheared.web.application import WebserverApplication
from sheared.web.collection import StaticCollection

articles = {
    1: {   'id': 1,
        'title': 'First post!',
          'text': 'Ha! This is the first post!'},
    2: {    'id': 2,
         'title': 'All...',
          'text': 'All your posts are belong to us!'},
}

class Page(Entwiner):
    def __init__(self):
        Entwiner.__init__(self)
        self.template_page = 'page.html'

class Index(Page):
    def entwine(self, request, reply, subpath):
        self.context['articles'] = articles.values()
        self.execute('index.html')

class Article(Page):
    def entwine(self, request, reply, subpath):
        id = request.args.get_one('id').as_int()

        self.context['article'] = articles[id]
        self.execute('article.html')

class Application(WebserverApplication):
    def configure(self):
        root = StaticCollection()
        root.bind('index', Index())
        root.bind('article', Article())
        return root

if __name__ == '__main__':
    Application().main()
