#!/usr/bin/env python-stackless

import os

from sheared.web.entwiner import Entwiner
from sheared.web.application import WebserverApplication
from sheared.web.collection import FilesystemCollection

options = [
    [ 'set_str', 1, 'docroot', 'r', 'document-root', 'webserver.document-root',
      'Root of directory tree that the web server will serve.' ],
]
class Application(WebserverApplication):
    def __init__(self):
        self.docroot = '~/public_html'
        WebserverApplication.__init__(self, None, options)

    def configure(self):
        return FilesystemCollection(os.path.expanduser(self.docroot))

if __name__ == '__main__':
    Application().main()
